/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desafiografos.forms;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.IOException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JEditorPane;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;

/**
 *
 * @author Henrique
 */
public class FrmInstrucoes extends javax.swing.JDialog
{

    /**
     * Creates new form FrmInstrucoes
     */
    public FrmInstrucoes(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        this.carregarDocumento(this.jEditorPane1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        cmdFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Convenções e Instruções de Uso");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowActivated(java.awt.event.WindowEvent evt)
            {
                form_windowActivated(evt);
            }
        });

        jEditorPane1.setEditable(false);
        jEditorPane1.setContentType("text/html"); // NOI18N
        jEditorPane1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jEditorPane1);

        cmdFechar.setText("Fechar");
        cmdFechar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                cmdFechar_mouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 555, Short.MAX_VALUE)
                .addComponent(cmdFechar))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdFechar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdFechar_mouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cmdFechar_mouseClicked
    {//GEN-HEADEREND:event_cmdFechar_mouseClicked
        this.dispose();
    }//GEN-LAST:event_cmdFechar_mouseClicked

    private void form_windowActivated(java.awt.event.WindowEvent evt)//GEN-FIRST:event_form_windowActivated
    {//GEN-HEADEREND:event_form_windowActivated
        jEditorPane1.requestFocus();
    }//GEN-LAST:event_form_windowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FrmInstrucoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FrmInstrucoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FrmInstrucoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FrmInstrucoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                FrmInstrucoes dialog = new FrmInstrucoes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdFechar;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void carregarDocumento(JEditorPane editor)
    {
        try
        {
            URL url = this.getClass().getResource("/desafiografos/recursos/instrucoes/instrucoes.htm");
            editor.setPage(url);
            editor.addHyperlinkListener(new HyperlinkListener() {
                @Override
                public void hyperlinkUpdate(HyperlinkEvent e)
                {
                    if (HyperlinkEvent.EventType.ACTIVATED == e.getEventType())
                    {
                        String desc = e.getDescription();
                        if (desc == null || !desc.startsWith("#")) return;
                        desc = desc.substring(1);
                        editor.scrollToReference(desc);
                    }
                }
            });
            editor.addKeyListener(new KeyListener()
            {
                @Override
                public void keyTyped(KeyEvent e)
                {
                }

                @Override
                public void keyPressed(KeyEvent e)
                {
                    switch(e.getKeyCode())
                    {
                        case KeyEvent.VK_UP:
                            break;
                        case KeyEvent.VK_DOWN:
                            break;
                        case KeyEvent.VK_HOME:
                            editor.setSelectionStart(0);
                            editor.setSelectionEnd(0);
                            break;
                        case KeyEvent.VK_END:
                            int fimDoTexto = editor.getText().length() - 1;
                            editor.setSelectionStart(fimDoTexto);
                            editor.setSelectionEnd(fimDoTexto);
                            break;
                    }
                }

                @Override
                public void keyReleased(KeyEvent e)
                {
                }
            });
        }
        catch (IOException ex)
        {
            Logger.getLogger(FrmInstrucoes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}

